spring:
  application:
    name: se-payment
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://masterpiece-masterpiece.b.aivencloud.com:17078/defaultdb?ssl=require
    username: avnadmin
    password: AVNS_ZYRRun0uv9c_yKkbmpd

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs       # endpoint JSON
  swagger-ui:
    enabled: true
    path: /swagger-ui.html   # endpoint UI
    operations-sorter: method
    tags-sorter: alpha

  info:
    title: Se-payment API
    description: API documentation for the Se-payment service
    version: 1.0.0
