spring:
  application:
    name: se-payment
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://sepaymentdb_user:GNueYjhDhDhxM5V5ZlTmKKYPxqs0AJIj@dpg-d3dtoqruibrs73bvo730-a/sepaymentdb
    username: sepaymentdb_user
    password: GNueYjhDhDhxM5V5ZlTmKKYPxqs0AJIj